name: Upload components to the registry

on:
  push:
    branches:
      - main

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@fix/dep-warning
        with:
          name: tmptst
          directories: cmp
          namespace: kumekay
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
