name: Upload components to the registry

on:
  push:
    tags:
      - v*

jobs:
  upload_components:
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: |
            cmp
          namespace: kumekay
          version: ${{ github.ref_name }}
          # api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}


